name: Build the project

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build with make
      working-directory: ./src
      run: make

    - name: Create release directory
      run: mkdir -p ./release

    - name: Move build output to release
      run: mv ./src/CRCHex ./release/

    - name: Check if there are changes
      id: verify_diff
      run: |
        git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT    

    - name: Commit and push changes
      if: steps.verify_diff.outputs.changed == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ./release
        git commit -m "Deploy build output to release directory"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
